# Generated by Django 2.2 on 2020-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='codigo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
