# Generated by Django 2.2 on 2020-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='id',
        ),
        migrations.AlterField(
            model_name='autor',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
