# Generated by Django 2.2 on 2020-05-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='codigo_autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Autor'),
            preserve_default=False,
        ),
    ]
