# Generated by Django 2.2 on 2020-05-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_libro_paginas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='codigo_autor',
            new_name='autor',
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('localizacion', models.CharField(max_length=50)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro')),
            ],
        ),
    ]
