# Generated by Django 2.2 on 2020-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20200514_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('ejemplares', models.ManyToManyField(to='biblioteca.Ejemplar')),
            ],
        ),
    ]
